#!/usr/bin/env node

const path = require('path');
const os = require('os');
const childProcess = require('child_process');
const files = require('./../../node/files');
const terminal = require('./../../node/terminal');

const currentDir = path.resolve(__dirname);
const homedir = os.homedir();

terminal.yellow('    * Installing zsh and zsh-completion');
childProcess.execSync('brew install zsh zsh-completion', [], { stdio: 'inherit' });

terminal.yellow('    * Installing curl');
childProcess.execSync('brew install curl', [], { stdio: 'inherit' });

terminal.yellow('    * Installing oh-my-zsh');
childProcess.execSync('sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"', [], { stdio: 'inherit' });

terminal.yellow('    * Copying configuration file');
files.createSymLink(path.join(currentDir, '.zshrc'), path.join(homedir, '.zshrc'));

process.exit(0);
