#!/usr/bin/env bash

source ./helpers.sh
DOTFILES=~/dotfiles

info "Installing neovim"
brew install nvim

info "Ruby configuration"
sudo gem install neovim

info "Python configuration"
brew install python
python3 -m pip install --user --upgrade pynvim

info "Installing packer"
git clone --depth 1 https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim

info "Linking all configuration files"
mkdir ~/.config/nvim
symlink "${DOTFILES}/installations/nvim/init.lua" ~/.config/nvim/init.lua
symlink "${DOTFILES}/installations/nvim/lua" ~/.config/nvim/lua

info "nvim installation complete."
info "Open nvim and run :PackerInstall to install plugins"

exit 0
