#!/usr/bin/env bash

source ./helpers.sh
DOTFILES=~/dotfiles

info "Installing neovim"
brew install neovim

info "Ruby configuration"
sudo gem install neovim

info "Python configuration"
brew install python
python3 -m pip install --user --upgrade pynvim


info "Linking all configuration files"
mkdir -p ~/.config/nvim
symlink "${DOTFILES}/installations/nvim/init.lua" ~/.config/nvim/init.lua
symlink "${DOTFILES}/installations/nvim/lua" ~/.config/nvim/lua
symlink "${DOTFILES}/installations/nvim/after" ~/.config/nvim/after
symlink "${DOTFILES}/installations/nvim/plugin" ~/.config/nvim/plugin

info "nvim installation complete."
info "Open nvim and run :Lazy to install plugins"
pause

exit 0
