#!/usr/bin/env bash

set -uo pipefail

source ./helpers.sh

# Creating links to configuration files
DOTFILES=~/dotfiles

info "Linking tmux configuration files"
symlink "${DOTFILES}/installations/tmux/.tmux.conf" ~/.tmux.conf
success "Finished linking configuration file"
pause

exit 0
