#!/usr/bin/env bash

source ./helpers.sh

# $HOME is the user's home directory: ~/
# This is the directory that this script file is in
CURRENT_DIR=$(dirname $0)


# If you want to install the latest version
# of neovim (which might be unstable) then
# uncomment the next line.
# brew install --HEAD neovim

# Check if neovim is installed
info "Checking if neovim is installed already"
which -s nvim
if [ $? != 0 ]; then
  info "Installing neovim..."
  brew install neovim

  if [ $? != 0 ]; then
    echo
    error "Failed to install neovim"
    echo "Try running 'brew install neovim' to see the error yourself"
    echo
    if ! confirm "Should I continue with the neovim configuration?"; then
      exit 1
    fi
  fi
else
  info "neovim is installed already"
  info "Update neovim"
  brew upgrade neovim

  if [ $? != 0 ]; then
    echo
    error "Failed to update neovim"
    echo "Try running 'brew upgrade neovim' to see the error yourself"
    echo
    if ! confirm "Should I continue with the neovim configuration?"; then
      exit 1
    fi
  fi
fi

info "Done installing/updating neovim."


# Now create link to settings files
info "Linking vim settings files"
symlink "$CURRENT_DIR/init.vim" "$HOME/.config/nvim/init.vim"

# Link vim color theme
info "Linking darcula color theme"
symlink "$CURRENT_DIR/darcula.vim" "$HOME/.config/nvim/colors/darcula.vim"

# Install all relevant plugins
info "Installing vim plugins"
vim +PlugInstall +UpdateRemotePlugins +qall

# Install coc.nvim extensions
extensions="coc-tsserver coc-eslint coc-json coc-html coc-css"
info "Installing Coc extensions... "
mkdir -p "$HOME/.config/coc/extensions"
cd "$HOME/.config/coc/extensions"
yarn add --ignore-engines $extensions
symlink "$CURRENT_DIR/coc-settings.json" "$HOME/.config/nvim/coc-settings.json"

exit 0
