#!/usr/bin/env bash

source ./helpers.sh

# If you want to install the latest version
# of neovim (which might be unstable) then
# uncomment the next line.
# brew install --HEAD neovim

# Check if neovim is installed
info "Checking if neovim is installed already"
which -s nvim
if [ $? != 0 ]; then
  info "Installing neovim..."
  brew install neovim

  if [ $? != 0 ]; then
    echo
    error "Failed to install neovim"
    echo "Try running 'brew install neovim' to see the error yourself"
    echo
    exit 1
  fi
else
  info "neovim is installed already"
  info "Update neovim"
  brew upgrade neovim

  if [ $? != 0 ]; then
    echo
    error "Failed to update neovim"
    echo "Try running 'brew upgrade neovim' to see the error yourself"
    echo
    exit 1
  fi
fi

info "Done installing/updating neovim."


# Now create link to settings files
info "Linking vim settings files"
symlink "./init.vim" "~/.config/nvim/init.vim"

# Link vim color theme
info "Linking darcula color theme"
symlink "./darcula.vim" "~/.config/nvim/colors/darcula.vim"

# Install all relevant plugins
info "Installing vim plugins"
vim +PlugInstall +UpdateRemotePlugins +qall

# Install coc.nvim extensions
extensions="coc-tsserver coc-eslint coc-json coc-html coc-css"
info "Installing Coc extensions... "
mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
yarn add --ignore-engines $extensions
symlink "./coc-settings.json" "~/.config/nvim/coc-settings.json"

exit 0
