#!/usr/bin/env bash

source ./helpers.sh

# Install neovim
brew install neovim

# If you want to install the latest version
# of neovim (which might be unstable) then
# uncomment the next line.
# brew install --HEAD neovim

if [ $? != 0 ]; then
  error "Failed to install neovim... :("
  exit 1
fi

# Now create link to settings files
info "Linking vim settings files"
symlink "./init.vim" "~/.config/nvim/init.vim"

# Link vim color theme
info "Linking darcula color theme"
symlink "./darcula.vim" "~/.config/nvim/colors/darcula.vim"

# Install all relevant plugins
info "Installing vim plugins"
vim +PlugInstall +UpdateRemotePlugins +qall

# Install coc.nvim extensions
extensions="coc-tsserver coc-eslint coc-json coc-html coc-css"
info "Installing Coc extensions... "
mkdir -p ~/.config/coc/extensions
cd ~/.config/coc/extensions
yarn add --ignore-engines $extensions
symlink "./coc-settings.json" "~/.config/nvim/coc-settings.json"
