#!/usr/bin/env bash

source ./helpers.sh

brew install --cask iterm2

if [ $? != 0 ]; then
  error "Failed to install iterm2... :("
  exit 1
fi

# Loads the terminfo file - so we have italics defined properly
tic ./xterm-256colo-italic.terminfo

# TODO: We can fix this so that the settings in iterm come from here..
# We have the settings files in this folder
# Now we just need to make the user configures
# iterm2 to take the settings files from here.
info "iterm2 installed successfully"
info "Settings files are here (in this dir)"
info "They are: 'com.googlecode.iterm2.plist', 'profile-settings.json'"
info "Set iterm2 to load the settings files from here, and make sure it works."
pause

exit 0
