#!/usr/bin/env bash

source ./helpers.sh

if [ -z $NO_GUI ]; then
  brew install --cask iterm2

  if [ $? != 0 ]; then
    error "Failed to install iterm2... :("
    exit 1
  fi

  # We have the settings files in this folder
  # Now we just need to make the user configures
  # iterm2 to take the settings files from here.
  info "iterm2 installed successfully"
  info "Settings files are here (in this dir)"
  info "They are: 'com.googlecode.iterm2.plist', 'profile-settings.json'"
  info "Set iterm2 to load the settings files from here, and make sure it works."

  if confirm "Did you do as you were told?"; then
    echo "Good boy"
    exit 0
  else
    echo "Not so good..."
    exit 1
  fi

else
  error "Can't install iterm2, because it requires a gui"
fi
