#!/usr/bin/env node

const path = require('path');
const os = require('os');
const files = require('./../../node/files.js');

const currentDir = path.resolve(__dirname);

files.createSymLink(path.join(currentDir, '.gitconfig'), path.join(os.homedir(), '.gitconfig'));
files.createSymLink(path.join(currentDir, '.gitignore_global'), path.join(os.homedir(), '.gitignore_global'));

process.exit(0);
